# Generated by Django 5.2.17 on 2026-08-23 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CI', 'Cédula de identidad'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro')], default='CI', max_length=10)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='patients.patient')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='tenancy.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'patients',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('organization', 'document_type', 'document_number'), name='uq_patient_document'), models.CheckConstraint(condition=models.Q(('guardian', models.F('id')), _negated=True), name='ck_patient_guardian'), models.UniqueConstraint(fields=('id', 'organization'), name='uq_patient_id_org'), models.CheckConstraint(condition=models.Q(('document_number__isnull', False), ('guardian__isnull', False), _connector='OR'), name='ck_patient_doc_or_guardian')],
            },
        ),
    ]
