# Generated by Django 5.2.17 on 2026-09-06 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_us07_dependents'),
        ('tenancy', '0003_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('allergy', 'Alergia'), ('condition', 'Condición crónica'), ('medication', 'Medicación habitual')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Grave'), ('anaphylactic', 'Anafiláctica')], default='', max_length=20)),
                ('source', models.CharField(choices=[('self_reported', 'Declarado por el paciente'), ('practitioner', 'Registrado por un profesional')], default='self_reported', max_length=20)),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_history_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_history_entries', to='tenancy.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='patients.patient')),
            ],
            options={
                'verbose_name': 'antecedente',
                'verbose_name_plural': 'antecedentes',
                'db_table': 'patient_history_entries',
                'ordering': ['kind', '-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='ix_history_patient')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind', 'allergy'), ('severity', ''), _connector='OR'), name='ck_history_severity')],
            },
        ),
    ]
