# Generated by Django 5.2.17 on 2026-08-23 20:32

import accounts.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('document_type', models.CharField(choices=[('CI', 'Cédula de identidad'), ('PAS', 'Pasaporte'), ('NIT', 'NIT'), ('OTRO', 'Otro')], default='CI', max_length=10)),
                ('document_number', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'users',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('entity', models.CharField(max_length=60)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'entrada de bitácora',
                'verbose_name_plural': 'bitácora',
                'db_table': 'audit_log',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempted_email', models.CharField(max_length=254)),
                ('succeeded', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, choices=[('', 'Sin fallo'), ('bad_credentials', 'Credenciales incorrectas'), ('unknown_user', 'Usuario inexistente'), ('inactive_user', 'Usuario dado de baja'), ('locked', 'Cuenta bloqueada'), ('unknown_tenant', 'Organización inexistente'), ('inactive_tenant', 'Organización inactiva')], default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'intento de inicio de sesión',
                'verbose_name_plural': 'intentos de inicio de sesión',
                'db_table': 'login_attempts',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z_]+\\.[a-z_]+\\.[a-z_]+$', 'Formato: modulo.recurso.accion')])),
                ('module', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'db_table': 'permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'permiso de rol',
                'verbose_name_plural': 'permisos de rol',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'rol de usuario',
                'verbose_name_plural': 'roles de usuario',
                'db_table': 'user_roles',
            },
        ),
    ]
