# Generated by Django 5.2.17 on 2026-10-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_permissions_sprint_2_appointments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['assigned_at', 'id'], 'verbose_name': 'rol de usuario', 'verbose_name_plural': 'roles de usuario'},
        ),
    ]
