-- =========================================================================
--  ESQUEMA REAL DEL SPRINT 0, GENERADO POR DJANGO
--
--  Este archivo NO se escribio a mano y NO se ejecuta. Es la salida de
--
--      python manage.py sqlmigrate <app> <migracion>
--
--  es decir, exactamente el SQL que Django envio a PostgreSQL al correr
--  "manage.py migrate". Sirve para dos cosas:
--
--    1. la documentacion del proyecto (el DDL real, no una aproximacion),
--    2. leer o revisar el modelo desde el SQL Editor de Supabase.
--
--  El esquema se aplica SIEMPRE con "manage.py migrate", nunca pegando
--  este archivo en una consola. Si se ejecutara, Django despues querria
--  crear tablas que ya existen.
--
--  Para regenerarlo, ver el pie del archivo.
-- =========================================================================


-- =========================================================================
--  accounts / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model User
--
CREATE TABLE "users" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "email" varchar(254) NOT NULL, "first_name" varchar(80) NOT NULL, "last_name" varchar(80) NOT NULL, "document_type" varchar(10) NOT NULL, "document_number" varchar(20) NOT NULL, "phone" varchar(30) NOT NULL, "birth_date" date NULL, "is_platform_admin" boolean NOT NULL, "is_active" boolean NOT NULL, "failed_login_attempts" smallint NOT NULL CHECK ("failed_login_attempts" >= 0), "locked_until" timestamp with time zone NULL, "last_login_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model AuditLog
--
CREATE TABLE "audit_log" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(60) NOT NULL, "entity" varchar(60) NOT NULL, "entity_id" varchar(64) NOT NULL, "detail" jsonb NOT NULL, "ip_address" inet NULL, "occurred_at" timestamp with time zone NOT NULL);
--
-- Create model LoginAttempt
--
CREATE TABLE "login_attempts" ("id" uuid NOT NULL PRIMARY KEY, "attempted_email" varchar(254) NOT NULL, "succeeded" boolean NOT NULL, "failure_reason" varchar(40) NOT NULL, "ip_address" inet NULL, "user_agent" varchar(300) NOT NULL, "occurred_at" timestamp with time zone NOT NULL);
--
-- Create model Permission
--
CREATE TABLE "permissions" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(80) NOT NULL UNIQUE, "module" varchar(40) NOT NULL, "description" varchar(200) NOT NULL);
--
-- Create model Role
--
CREATE TABLE "roles" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(40) NOT NULL, "name" varchar(80) NOT NULL, "description" varchar(200) NOT NULL, "is_system" boolean NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model RolePermission
--
CREATE TABLE "role_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "granted_at" timestamp with time zone NOT NULL);
--
-- Create model UserRole
--
CREATE TABLE "user_roles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "assigned_at" timestamp with time zone NOT NULL);
CREATE INDEX "permissions_code_c5331a5c_like" ON "permissions" ("code" varchar_pattern_ops);
COMMIT;

-- =========================================================================
--  tenancy / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model SubscriptionPlan
--
CREATE TABLE "subscription_plans" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(30) NOT NULL UNIQUE, "name" varchar(80) NOT NULL, "description" text NOT NULL, "monthly_price" numeric(10, 2) NOT NULL, "currency" varchar(3) NOT NULL, "max_branches" integer NULL CHECK ("max_branches" >= 0), "max_users" integer NULL CHECK ("max_users" >= 0), "max_practitioners" integer NULL CHECK ("max_practitioners" >= 0), "max_appointments_month" integer NULL CHECK ("max_appointments_month" >= 0), "max_ai_queries_month" integer NULL CHECK ("max_ai_queries_month" >= 0), "storage_mb" integer NULL CHECK ("storage_mb" >= 0), "features" jsonb NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model Organization
--
CREATE TABLE "organizations" ("id" uuid NOT NULL PRIMARY KEY, "slug" varchar(40) NOT NULL UNIQUE, "name" varchar(120) NOT NULL, "legal_name" varchar(160) NOT NULL, "tax_id" varchar(20) NOT NULL UNIQUE, "contact_email" varchar(254) NOT NULL, "contact_phone" varchar(30) NOT NULL, "address" varchar(200) NOT NULL, "city" varchar(80) NOT NULL, "country" varchar(2) NOT NULL, "logo_url" varchar(300) NOT NULL, "primary_color" varchar(7) NOT NULL, "secondary_color" varchar(7) NOT NULL, "timezone" varchar(40) NOT NULL, "status" varchar(12) NOT NULL, "onboarded_at" date NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, CONSTRAINT "ck_organization_status" CHECK ("status" IN ('active', 'suspended', 'inactive')));
--
-- Create model IsolationAlert
--
CREATE TABLE "isolation_alerts" ("id" uuid NOT NULL PRIMARY KEY, "alert_type" varchar(40) NOT NULL, "severity" varchar(10) NOT NULL, "description" varchar(300) NOT NULL, "endpoint" varchar(200) NOT NULL, "http_method" varchar(10) NOT NULL, "ip_address" inet NULL, "detail" jsonb NOT NULL, "status" varchar(12) NOT NULL, "occurred_at" timestamp with time zone NOT NULL, "resolved_at" timestamp with time zone NULL, "resolution_note" varchar(300) NOT NULL, "resolved_by_id" uuid NULL, "user_id" uuid NULL, "source_organization_id" uuid NULL, "target_organization_id" uuid NULL, CONSTRAINT "ck_alert_resolution" CHECK ((("resolved_at" IS NOT NULL AND "status" IN ('resolved', 'dismissed')) OR (NOT ("status" IN ('resolved', 'dismissed')) AND "resolved_at" IS NULL))));
--
-- Create model Subscription
--
CREATE TABLE "subscriptions" ("id" uuid NOT NULL PRIMARY KEY, "starts_at" date NOT NULL, "ends_at" date NULL, "status" varchar(12) NOT NULL, "change_reason" varchar(200) NOT NULL, "created_at" timestamp with time zone NOT NULL, "assigned_by_id" uuid NULL, "organization_id" uuid NOT NULL, "plan_id" uuid NOT NULL, CONSTRAINT "ck_subscription_period" CHECK (("ends_at" IS NULL OR "ends_at" >= ("starts_at"))));
--
-- Create model UsageMetric
--
CREATE TABLE "usage_metrics" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "metric_code" varchar(40) NOT NULL, "granularity" varchar(10) NOT NULL, "period_start" date NOT NULL, "value" numeric(14, 2) NOT NULL, "computed_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "uq_usage_metric" UNIQUE ("organization_id", "metric_code", "granularity", "period_start"));
CREATE INDEX "subscription_plans_code_28233073_like" ON "subscription_plans" ("code" varchar_pattern_ops);
CREATE INDEX "organizations_slug_aaafa6fa_like" ON "organizations" ("slug" varchar_pattern_ops);
CREATE INDEX "organizations_tax_id_8cb0fd40_like" ON "organizations" ("tax_id" varchar_pattern_ops);
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_resolved_by_id_6ae6191c_fk_users_id" FOREIGN KEY ("resolved_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_user_id_b9705ed8_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_source_organization__01300ea4_fk_organizat" FOREIGN KEY ("source_organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_target_organization__0accec3f_fk_organizat" FOREIGN KEY ("target_organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "isolation_alerts_resolved_by_id_6ae6191c" ON "isolation_alerts" ("resolved_by_id");
CREATE INDEX "isolation_alerts_user_id_b9705ed8" ON "isolation_alerts" ("user_id");
CREATE INDEX "isolation_alerts_source_organization_id_01300ea4" ON "isolation_alerts" ("source_organization_id");
CREATE INDEX "isolation_alerts_target_organization_id_0accec3f" ON "isolation_alerts" ("target_organization_id");
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_assigned_by_id_43e466d2_fk_users_id" FOREIGN KEY ("assigned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_organization_id_b8dfd38b_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_plan_id_b857580e_fk_subscription_plans_id" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX "uq_subscription_active" ON "subscriptions" ("organization_id") WHERE "ends_at" IS NULL;
CREATE INDEX "subscriptions_assigned_by_id_43e466d2" ON "subscriptions" ("assigned_by_id");
CREATE INDEX "subscriptions_organization_id_b8dfd38b" ON "subscriptions" ("organization_id");
CREATE INDEX "subscriptions_plan_id_b857580e" ON "subscriptions" ("plan_id");
ALTER TABLE "usage_metrics" ADD CONSTRAINT "usage_metrics_organization_id_00852865_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usage_metrics_organization_id_00852865" ON "usage_metrics" ("organization_id");
CREATE INDEX "ix_usage_metrics_period" ON "usage_metrics" ("period_start" DESC, "metric_code");
COMMIT;

-- =========================================================================
--  catalog / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model Branch
--
CREATE TABLE "branches" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(120) NOT NULL, "address" varchar(200) NOT NULL, "phone" varchar(30) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "uq_branch_name" UNIQUE ("organization_id", "name"), CONSTRAINT "uq_branch_id_org" UNIQUE ("id", "organization_id"));
ALTER TABLE "branches" ADD CONSTRAINT "branches_organization_id_49dd869c_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "branches_organization_id_49dd869c" ON "branches" ("organization_id");
COMMIT;

-- =========================================================================
--  accounts / 0002_initial
-- =========================================================================

BEGIN;
--
-- Add field branch to user
--
ALTER TABLE "users" ADD COLUMN "branch_id" uuid NULL CONSTRAINT "users_branch_id_d1b397ca_fk_branches_id" REFERENCES "branches"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_branch_id_d1b397ca_fk_branches_id" IMMEDIATE;
--
-- Add field organization to user
--
ALTER TABLE "users" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "users_organization_id_abe5d649_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_organization_id_abe5d649_fk_organizations_id" IMMEDIATE;
--
-- Add field organization to auditlog
--
ALTER TABLE "audit_log" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "audit_log_organization_id_385c33bb_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "audit_log_organization_id_385c33bb_fk_organizations_id" IMMEDIATE;
--
-- Add field user to auditlog
--
ALTER TABLE "audit_log" ADD COLUMN "user_id" uuid NULL CONSTRAINT "audit_log_user_id_a1b3392d_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "audit_log_user_id_a1b3392d_fk_users_id" IMMEDIATE;
--
-- Add field organization to loginattempt
--
ALTER TABLE "login_attempts" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "login_attempts_organization_id_43fcb601_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "login_attempts_organization_id_43fcb601_fk_organizations_id" IMMEDIATE;
--
-- Add field user to loginattempt
--
ALTER TABLE "login_attempts" ADD COLUMN "user_id" uuid NULL CONSTRAINT "login_attempts_user_id_8779072f_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "login_attempts_user_id_8779072f_fk_users_id" IMMEDIATE;
--
-- Add field organization to role
--
ALTER TABLE "roles" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "roles_organization_id_4b873032_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "roles_organization_id_4b873032_fk_organizations_id" IMMEDIATE;
--
-- Add field organization to rolepermission
--
ALTER TABLE "role_permissions" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "role_permissions_organization_id_bdb9f9aa_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "role_permissions_organization_id_bdb9f9aa_fk_organizations_id" IMMEDIATE;
--
-- Add field permission to rolepermission
--
ALTER TABLE "role_permissions" ADD COLUMN "permission_id" uuid NOT NULL CONSTRAINT "role_permissions_permission_id_ad343843_fk_permissions_id" REFERENCES "permissions"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "role_permissions_permission_id_ad343843_fk_permissions_id" IMMEDIATE;
--
-- Add field role to rolepermission
--
ALTER TABLE "role_permissions" ADD COLUMN "role_id" uuid NOT NULL CONSTRAINT "role_permissions_role_id_216516f2_fk_roles_id" REFERENCES "roles"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "role_permissions_role_id_216516f2_fk_roles_id" IMMEDIATE;
--
-- Add field assigned_by to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "assigned_by_id" uuid NULL CONSTRAINT "user_roles_assigned_by_id_a9db12d1_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_assigned_by_id_a9db12d1_fk_users_id" IMMEDIATE;
--
-- Add field organization to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "user_roles_organization_id_fe06d974_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_organization_id_fe06d974_fk_organizations_id" IMMEDIATE;
--
-- Add field role to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "role_id" uuid NOT NULL CONSTRAINT "user_roles_role_id_816a4486_fk_roles_id" REFERENCES "roles"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_role_id_816a4486_fk_roles_id" IMMEDIATE;
--
-- Add field user to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "user_id" uuid NOT NULL CONSTRAINT "user_roles_user_id_9d9f8dbb_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_user_id_9d9f8dbb_fk_users_id" IMMEDIATE;
--
-- Create constraint uq_user_email on model user
--
ALTER TABLE "users" ADD CONSTRAINT "uq_user_email" UNIQUE ("organization_id", "email");
--
-- Create constraint uq_user_document on model user
--
ALTER TABLE "users" ADD CONSTRAINT "uq_user_document" UNIQUE ("organization_id", "document_number");
--
-- Create constraint uq_user_email_platform on model user
--
CREATE UNIQUE INDEX "uq_user_email_platform" ON "users" ("email") WHERE "organization_id" IS NULL;
--
-- Create constraint uq_user_id_org on model user
--
ALTER TABLE "users" ADD CONSTRAINT "uq_user_id_org" UNIQUE ("id", "organization_id");
--
-- Create constraint ck_user_scope on model user
--
ALTER TABLE "users" ADD CONSTRAINT "ck_user_scope" CHECK ((("is_platform_admin" AND "organization_id" IS NULL) OR (NOT "is_platform_admin" AND "organization_id" IS NOT NULL)));
--
-- Create index ix_audit_log_org on field(s) organization, -occurred_at of model auditlog
--
CREATE INDEX "ix_audit_log_org" ON "audit_log" ("organization_id", "occurred_at" DESC);
--
-- Create index ix_login_attempts_email on field(s) attempted_email, -occurred_at of model loginattempt
--
CREATE INDEX "ix_login_attempts_email" ON "login_attempts" ("attempted_email", "occurred_at" DESC);
--
-- Create constraint uq_role_code_org on model role
--
CREATE UNIQUE INDEX "uq_role_code_org" ON "roles" ("organization_id", "code") WHERE "organization_id" IS NOT NULL;
--
-- Create constraint uq_role_code_system on model role
--
CREATE UNIQUE INDEX "uq_role_code_system" ON "roles" ("code") WHERE "organization_id" IS NULL;
--
-- Create constraint ck_role_system on model role
--
ALTER TABLE "roles" ADD CONSTRAINT "ck_role_system" CHECK ((NOT "is_system" OR "organization_id" IS NULL));
--
-- Create constraint uq_role_id_org on model role
--
ALTER TABLE "roles" ADD CONSTRAINT "uq_role_id_org" UNIQUE ("id", "organization_id");
--
-- Create constraint uq_role_permission on model rolepermission
--
ALTER TABLE "role_permissions" ADD CONSTRAINT "uq_role_permission" UNIQUE ("role_id", "permission_id");
--
-- Create constraint uq_user_role on model userrole
--
ALTER TABLE "user_roles" ADD CONSTRAINT "uq_user_role" UNIQUE ("user_id", "role_id");
CREATE INDEX "users_branch_id_d1b397ca" ON "users" ("branch_id");
CREATE INDEX "users_organization_id_abe5d649" ON "users" ("organization_id");
CREATE INDEX "audit_log_organization_id_385c33bb" ON "audit_log" ("organization_id");
CREATE INDEX "audit_log_user_id_a1b3392d" ON "audit_log" ("user_id");
CREATE INDEX "login_attempts_organization_id_43fcb601" ON "login_attempts" ("organization_id");
CREATE INDEX "login_attempts_user_id_8779072f" ON "login_attempts" ("user_id");
CREATE INDEX "roles_organization_id_4b873032" ON "roles" ("organization_id");
CREATE INDEX "role_permissions_organization_id_bdb9f9aa" ON "role_permissions" ("organization_id");
CREATE INDEX "role_permissions_permission_id_ad343843" ON "role_permissions" ("permission_id");
CREATE INDEX "role_permissions_role_id_216516f2" ON "role_permissions" ("role_id");
CREATE INDEX "user_roles_assigned_by_id_a9db12d1" ON "user_roles" ("assigned_by_id");
CREATE INDEX "user_roles_organization_id_fe06d974" ON "user_roles" ("organization_id");
CREATE INDEX "user_roles_role_id_816a4486" ON "user_roles" ("role_id");
CREATE INDEX "user_roles_user_id_9d9f8dbb" ON "user_roles" ("user_id");
COMMIT;

-- =========================================================================
--  patients / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model Patient
--
CREATE TABLE "patients" ("id" uuid NOT NULL PRIMARY KEY, "document_type" varchar(10) NOT NULL, "document_number" varchar(20) NULL, "first_name" varchar(80) NOT NULL, "last_name" varchar(80) NOT NULL, "birth_date" date NULL, "sex" varchar(1) NULL, "phone" varchar(30) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "guardian_id" uuid NULL, "organization_id" uuid NOT NULL, "user_id" uuid NULL UNIQUE, CONSTRAINT "ck_patient_guardian" CHECK (NOT ("guardian_id" = ("id") AND "guardian_id" IS NOT NULL)), CONSTRAINT "uq_patient_id_org" UNIQUE ("id", "organization_id"), CONSTRAINT "ck_patient_doc_or_guardian" CHECK (("document_number" IS NOT NULL OR "guardian_id" IS NOT NULL)));
ALTER TABLE "patients" ADD CONSTRAINT "patients_guardian_id_0190b7d7_fk_patients_id" FOREIGN KEY ("guardian_id") REFERENCES "patients" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "patients" ADD CONSTRAINT "patients_organization_id_a6f5b5b9_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "patients" ADD CONSTRAINT "patients_user_id_11c42fa7_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX "uq_patient_document" ON "patients" ("organization_id", "document_type", "document_number") WHERE "document_number" IS NOT NULL;
CREATE INDEX "patients_guardian_id_0190b7d7" ON "patients" ("guardian_id");
CREATE INDEX "patients_organization_id_a6f5b5b9" ON "patients" ("organization_id");
COMMIT;

-- =========================================================================
--  tenancy / 0002_rls_policies
-- =========================================================================

BEGIN;
--
-- Raw SQL operation
--

CREATE OR REPLACE FUNCTION app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE
    AS $fn$ SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid $fn$;

CREATE OR REPLACE FUNCTION app_is_platform_admin() RETURNS boolean
    LANGUAGE sql STABLE
    AS $fn$ SELECT coalesce(current_setting('app.is_platform_admin', true) = 'on', false) $fn$;

-- Resuelve el inquilino a partir de su slug, para el formulario de login.
--
-- Existe por un problema del huevo y la gallina: antes de autenticar no hay
-- contexto, así que un SELECT sobre organizations devolvería cero filas por
-- la propia política, y el login nunca podría empezar.
--
-- Devuelve UNA columna —el uuid— y sólo de organizaciones activas. No permite
-- enumerar: hay que conocer el slug exacto de antemano. El permiso de
-- plataforma se activa y se restaura dentro de la misma llamada, de modo que
-- no sobrevive al retorno de la función.
CREATE OR REPLACE FUNCTION app_resolve_tenant(p_slug text) RETURNS uuid
    LANGUAGE plpgsql VOLATILE
    AS $fn$
DECLARE
    v_id   uuid;
    v_prev text;
BEGIN
    v_prev := coalesce(current_setting('app.is_platform_admin', true), '');
    PERFORM set_config('app.is_platform_admin', 'on', true);
    SELECT id INTO v_id FROM organizations
     WHERE slug = p_slug AND status = 'active';
    PERFORM set_config('app.is_platform_admin', v_prev, true);
    RETURN v_id;
END
$fn$;

--
-- Raw SQL operation
--

-- users.branch debe pertenecer a la misma organización que el usuario.
DO $do$
DECLARE c text;
BEGIN
    SELECT conname INTO c FROM pg_constraint
     WHERE conrelid = 'users'::regclass AND contype = 'f'
       AND confrelid = 'branches'::regclass;
    IF c IS NOT NULL THEN
        EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', c);
    END IF;
END
$do$;

ALTER TABLE users ADD CONSTRAINT fk_user_branch_same_org
    FOREIGN KEY (branch_id, organization_id)
    REFERENCES branches (id, organization_id) ON DELETE SET NULL (branch_id);

-- patients.user debe pertenecer a la misma organización que el paciente.
DO $do$
DECLARE c text;
BEGIN
    SELECT conname INTO c FROM pg_constraint
     WHERE conrelid = 'patients'::regclass AND contype = 'f'
       AND confrelid = 'users'::regclass;
    IF c IS NOT NULL THEN
        EXECUTE format('ALTER TABLE patients DROP CONSTRAINT %I', c);
    END IF;
END
$do$;

ALTER TABLE patients ADD CONSTRAINT fk_patient_user_same_org
    FOREIGN KEY (user_id, organization_id)
    REFERENCES users (id, organization_id) ON DELETE SET NULL (user_id);

-- El titular de un paciente debe ser de la misma organización.
DO $do$
DECLARE c text;
BEGIN
    SELECT conname INTO c FROM pg_constraint
     WHERE conrelid = 'patients'::regclass AND contype = 'f'
       AND confrelid = 'patients'::regclass;
    IF c IS NOT NULL THEN
        EXECUTE format('ALTER TABLE patients DROP CONSTRAINT %I', c);
    END IF;
END
$do$;

ALTER TABLE patients ADD CONSTRAINT fk_patient_guardian_same_org
    FOREIGN KEY (guardian_id, organization_id)
    REFERENCES patients (id, organization_id) ON DELETE SET NULL (guardian_id);

-- Un inquilino no puede asignarse un rol de otro.
DO $do$
DECLARE c text;
BEGIN
    FOR c IN
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'role_permissions'::regclass AND contype = 'f'
           AND confrelid = 'roles'::regclass
    LOOP
        EXECUTE format('ALTER TABLE role_permissions DROP CONSTRAINT %I', c);
    END LOOP;
    FOR c IN
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'user_roles'::regclass AND contype = 'f'
           AND confrelid = 'roles'::regclass
    LOOP
        EXECUTE format('ALTER TABLE user_roles DROP CONSTRAINT %I', c);
    END LOOP;
END
$do$;

ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permission_role_same_org
    FOREIGN KEY (role_id, organization_id)
    REFERENCES roles (id, organization_id) ON DELETE CASCADE;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_role_role_same_org
    FOREIGN KEY (role_id, organization_id)
    REFERENCES roles (id, organization_id) ON DELETE RESTRICT;

--
-- Raw SQL operation
--

CREATE OR REPLACE VIEW v_organization_current_plan AS
SELECT o.id        AS organization_id,
       o.name      AS organization_name,
       o.status    AS organization_status,
       o.onboarded_at,
       s.id        AS subscription_id,
       s.starts_at AS subscription_starts_at,
       p.id        AS plan_id,
       p.code      AS plan_code,
       p.name      AS plan_name,
       p.max_users,
       p.max_branches,
       p.max_appointments_month,
       p.max_ai_queries_month,
       p.storage_mb
FROM organizations o
LEFT JOIN subscriptions s
       ON s.organization_id = o.id AND s.ends_at IS NULL
LEFT JOIN subscription_plans p
       ON p.id = s.plan_id;

--
-- Raw SQL operation
--

            ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
            ALTER TABLE branches FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON branches
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
            ALTER TABLE roles FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON roles
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
            ALTER TABLE role_permissions FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON role_permissions
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
            ALTER TABLE user_roles FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON user_roles
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
            ALTER TABLE patients FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON patients
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

-- roles y role_permissions: las plantillas del sistema (organization_id NULL)
-- las LEE cualquier inquilino, para poder clonarlas al dar de alta una
-- organización; sólo el superadministrador las ESCRIBE.
--
-- Sin la política de escritura, la migración semilla falla: Django corre las
-- migraciones como app_user, sujeto a RLS.
CREATE POLICY system_templates_read ON roles
    FOR SELECT USING (organization_id IS NULL);
CREATE POLICY system_templates_write ON roles
    USING (organization_id IS NULL AND app_is_platform_admin())
    WITH CHECK (organization_id IS NULL AND app_is_platform_admin());

CREATE POLICY system_templates_read ON role_permissions
    FOR SELECT USING (organization_id IS NULL);
CREATE POLICY system_templates_write ON role_permissions
    USING (organization_id IS NULL AND app_is_platform_admin())
    WITH CHECK (organization_id IS NULL AND app_is_platform_admin());

-- users: el superadministrador debe poder verse a sí mismo para iniciar
-- sesión, pero no a los usuarios de ninguna organización.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON users
    USING (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    )
    WITH CHECK (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    );

-- audit_log: mismo patrón que users. El superadministrador audita sus propias
-- acciones (alta de organización, asignación de plan) con organization_id
-- NULL, y no ve la bitácora de ningún inquilino.
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON audit_log
    USING (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    )
    WITH CHECK (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    );

-- organizations: el superadmin las administra todas; cada inquilino sólo lee
-- su propia ficha, que necesita para el logo y los colores.
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations FORCE  ROW LEVEL SECURITY;
CREATE POLICY platform_admin_all ON organizations
    USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
CREATE POLICY tenant_reads_itself ON organizations
    FOR SELECT USING (id = app_current_tenant());

-- subscription_plans: catálogo legible por todos, escribible sólo por el
-- superadministrador.
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans FORCE  ROW LEVEL SECURITY;
CREATE POLICY plans_readable ON subscription_plans FOR SELECT USING (true);
CREATE POLICY plans_writable ON subscription_plans
    USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());

--
-- Raw SQL operation
--

            ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
            ALTER TABLE subscriptions FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_all ON subscriptions
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY tenant_reads_itself ON subscriptions
                FOR SELECT USING (organization_id = app_current_tenant());
        

            ALTER TABLE usage_metrics ENABLE ROW LEVEL SECURITY;
            ALTER TABLE usage_metrics FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_all ON usage_metrics
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY tenant_reads_itself ON usage_metrics
                FOR SELECT USING (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

            ALTER TABLE isolation_alerts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE isolation_alerts FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_manages ON isolation_alerts
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY anyone_reports ON isolation_alerts
                FOR INSERT WITH CHECK (true);
        

            ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE login_attempts FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_manages ON login_attempts
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY anyone_reports ON login_attempts
                FOR INSERT WITH CHECK (true);
        
--
-- Raw SQL operation
--

REVOKE UPDATE, DELETE ON audit_log      FROM CURRENT_USER;
REVOKE UPDATE, DELETE ON login_attempts FROM CURRENT_USER;

COMMIT;

-- =========================================================================
--  tenancy / 0003_seed_catalog
-- =========================================================================

BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  accounts / 0003_seed_permissions_sprint_1
-- =========================================================================

BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  accounts / 0004_password_reset_token
-- =========================================================================

BEGIN;
--
-- Create model PasswordResetToken
--
CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL PRIMARY KEY, "token_hash" varchar(64) NOT NULL UNIQUE, "expires_at" timestamp with time zone NOT NULL, "used_at" timestamp with time zone NULL, "ip_address" inet NULL, "created_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Raw SQL operation
--

ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON password_reset_tokens
    USING (organization_id = app_current_tenant())
    WITH CHECK (organization_id = app_current_tenant());

-- Un token no puede apuntar al usuario de otra organización.
--
-- Django crea una clave foránea simple contra users(id). Se la reemplaza por
-- la compuesta (user_id, organization_id), que es la que impide que una fila
-- de un inquilino referencie a un usuario de otro. Es el mismo patrón que
-- `fk_user_role_role_same_org`, y lo que lo hace posible es la restricción
-- `uq_user_id_org` de la tabla users.
DO $do$
DECLARE c text;
BEGIN
    FOR c IN
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'password_reset_tokens'::regclass AND contype = 'f'
           AND confrelid = 'users'::regclass
    LOOP
        EXECUTE format('ALTER TABLE password_reset_tokens DROP CONSTRAINT %I', c);
    END LOOP;
END
$do$;

ALTER TABLE password_reset_tokens ADD CONSTRAINT fk_password_reset_user_same_org
    FOREIGN KEY (user_id, organization_id)
    REFERENCES users (id, organization_id) ON DELETE CASCADE;

ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_token_organization_id_313e4305_fk_organizat" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_0aeaaad3_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "password_reset_tokens_token_hash_27f0c266_like" ON "password_reset_tokens" ("token_hash" varchar_pattern_ops);
CREATE INDEX "password_reset_tokens_organization_id_313e4305" ON "password_reset_tokens" ("organization_id");
CREATE INDEX "password_reset_tokens_user_id_0aeaaad3" ON "password_reset_tokens" ("user_id");
CREATE INDEX "ix_password_reset_user" ON "password_reset_tokens" ("user_id", "created_at" DESC);
COMMIT;

-- =========================================================================
--  catalog / 0002_catalogo_sprint_1
-- =========================================================================

BEGIN;
--
-- Add field latitude to branch
--
ALTER TABLE "branches" ADD COLUMN "latitude" numeric(9, 6) NULL;
--
-- Add field longitude to branch
--
ALTER TABLE "branches" ADD COLUMN "longitude" numeric(9, 6) NULL;
--
-- Add field timezone to branch
--
ALTER TABLE "branches" ADD COLUMN "timezone" varchar(40) DEFAULT 'America/La_Paz' NOT NULL;
ALTER TABLE "branches" ALTER COLUMN "timezone" DROP DEFAULT;
--
-- Create model Practitioner
--
CREATE TABLE "practitioners" ("id" uuid NOT NULL PRIMARY KEY, "first_name" varchar(80) NOT NULL, "last_name" varchar(80) NOT NULL, "license_number" varchar(40) NOT NULL, "search_name" varchar(170) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, "user_id" uuid NULL UNIQUE);
--
-- Create model PractitionerBranch
--
CREATE TABLE "practitioner_branches" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "branch_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "practitioner_id" uuid NOT NULL);
--
-- Add field branches to practitioner
--
-- (no-op)
--
-- Create model Specialty
--
CREATE TABLE "specialties" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(120) NOT NULL, "description" text NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL);
--
-- Create model PractitionerSpecialty
--
CREATE TABLE "practitioner_specialties" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, "practitioner_id" uuid NOT NULL, "specialty_id" uuid NOT NULL);
--
-- Add field specialties to practitioner
--
-- (no-op)
--
-- Create model BranchHours
--
CREATE TABLE "branch_hours" ("id" uuid NOT NULL PRIMARY KEY, "weekday" smallint NOT NULL CHECK ("weekday" >= 0), "opens_at" time NOT NULL, "closes_at" time NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "branch_id" uuid NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "ck_branch_hours_weekday" CHECK (("weekday" >= 0 AND "weekday" <= 6)), CONSTRAINT "ck_branch_hours_order" CHECK ("closes_at" > ("opens_at")));
--
-- Create constraint uq_practitioner_branch on model practitionerbranch
--
ALTER TABLE "practitioner_branches" ADD CONSTRAINT "uq_practitioner_branch" UNIQUE ("practitioner_id", "branch_id");
--
-- Create constraint uq_specialty_name on model specialty
--
ALTER TABLE "specialties" ADD CONSTRAINT "uq_specialty_name" UNIQUE ("organization_id", "name");
--
-- Create constraint uq_specialty_id_org on model specialty
--
ALTER TABLE "specialties" ADD CONSTRAINT "uq_specialty_id_org" UNIQUE ("id", "organization_id");
--
-- Create constraint uq_practitioner_specialty on model practitionerspecialty
--
ALTER TABLE "practitioner_specialties" ADD CONSTRAINT "uq_practitioner_specialty" UNIQUE ("practitioner_id", "specialty_id");
--
-- Create constraint uq_practitioner_id_org on model practitioner
--
ALTER TABLE "practitioners" ADD CONSTRAINT "uq_practitioner_id_org" UNIQUE ("id", "organization_id");
--
-- Create constraint uq_practitioner_license on model practitioner
--
CREATE UNIQUE INDEX "uq_practitioner_license" ON "practitioners" ("organization_id", "license_number") WHERE NOT ("license_number" = '');
ALTER TABLE "practitioners" ADD CONSTRAINT "practitioners_organization_id_1a52a049_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "practitioners" ADD CONSTRAINT "practitioners_user_id_210fa2d8_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "practitioners_organization_id_1a52a049" ON "practitioners" ("organization_id");
ALTER TABLE "practitioner_branches" ADD CONSTRAINT "practitioner_branches_branch_id_e9243fad_fk_branches_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "practitioner_branches" ADD CONSTRAINT "practitioner_branche_organization_id_95c71285_fk_organizat" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "practitioner_branches" ADD CONSTRAINT "practitioner_branche_practitioner_id_addf2b1c_fk_practitio" FOREIGN KEY ("practitioner_id") REFERENCES "practitioners" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "practitioner_branches_branch_id_e9243fad" ON "practitioner_branches" ("branch_id");
CREATE INDEX "practitioner_branches_organization_id_95c71285" ON "practitioner_branches" ("organization_id");
CREATE INDEX "practitioner_branches_practitioner_id_addf2b1c" ON "practitioner_branches" ("practitioner_id");
ALTER TABLE "specialties" ADD CONSTRAINT "specialties_organization_id_c0bc428b_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "specialties_organization_id_c0bc428b" ON "specialties" ("organization_id");
ALTER TABLE "practitioner_specialties" ADD CONSTRAINT "practitioner_special_organization_id_cd9acf00_fk_organizat" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "practitioner_specialties" ADD CONSTRAINT "practitioner_special_practitioner_id_9cbf835e_fk_practitio" FOREIGN KEY ("practitioner_id") REFERENCES "practitioners" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "practitioner_specialties" ADD CONSTRAINT "practitioner_special_specialty_id_5425addd_fk_specialti" FOREIGN KEY ("specialty_id") REFERENCES "specialties" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "practitioner_specialties_organization_id_cd9acf00" ON "practitioner_specialties" ("organization_id");
CREATE INDEX "practitioner_specialties_practitioner_id_9cbf835e" ON "practitioner_specialties" ("practitioner_id");
CREATE INDEX "practitioner_specialties_specialty_id_5425addd" ON "practitioner_specialties" ("specialty_id");
ALTER TABLE "branch_hours" ADD CONSTRAINT "branch_hours_branch_id_797750c4_fk_branches_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "branch_hours" ADD CONSTRAINT "branch_hours_organization_id_7d054123_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "branch_hours_branch_id_797750c4" ON "branch_hours" ("branch_id");
CREATE INDEX "branch_hours_organization_id_7d054123" ON "branch_hours" ("organization_id");
COMMIT;

-- =========================================================================
--  catalog / 0003_rls_policies
-- =========================================================================

BEGIN;
--
-- Raw SQL operation
--

            ALTER TABLE branch_hours ENABLE ROW LEVEL SECURITY;
            ALTER TABLE branch_hours FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON branch_hours
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE specialties ENABLE ROW LEVEL SECURITY;
            ALTER TABLE specialties FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON specialties
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE practitioners ENABLE ROW LEVEL SECURITY;
            ALTER TABLE practitioners FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON practitioners
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE practitioner_specialties ENABLE ROW LEVEL SECURITY;
            ALTER TABLE practitioner_specialties FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON practitioner_specialties
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE practitioner_branches ENABLE ROW LEVEL SECURITY;
            ALTER TABLE practitioner_branches FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON practitioner_branches
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'practitioners'::regclass AND contype = 'f'
               AND confrelid = 'users'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'practitioners'::regclass AND attname = 'user_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE practitioners DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE practitioners ADD CONSTRAINT fk_practitioners_users_same_org
        FOREIGN KEY (user_id, organization_id)
        REFERENCES users (id, organization_id) ON DELETE SET NULL (user_id);
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'branch_hours'::regclass AND contype = 'f'
               AND confrelid = 'branches'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'branch_hours'::regclass AND attname = 'branch_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE branch_hours DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE branch_hours ADD CONSTRAINT fk_branch_hours_branches_same_org
        FOREIGN KEY (branch_id, organization_id)
        REFERENCES branches (id, organization_id) ON DELETE CASCADE;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'practitioner_specialties'::regclass AND contype = 'f'
               AND confrelid = 'practitioners'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'practitioner_specialties'::regclass AND attname = 'practitioner_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE practitioner_specialties DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE practitioner_specialties ADD CONSTRAINT fk_practitioner_specialties_practitioners_same_org
        FOREIGN KEY (practitioner_id, organization_id)
        REFERENCES practitioners (id, organization_id) ON DELETE CASCADE;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'practitioner_specialties'::regclass AND contype = 'f'
               AND confrelid = 'specialties'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'practitioner_specialties'::regclass AND attname = 'specialty_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE practitioner_specialties DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE practitioner_specialties ADD CONSTRAINT fk_practitioner_specialties_specialties_same_org
        FOREIGN KEY (specialty_id, organization_id)
        REFERENCES specialties (id, organization_id) ON DELETE CASCADE;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'practitioner_branches'::regclass AND contype = 'f'
               AND confrelid = 'practitioners'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'practitioner_branches'::regclass AND attname = 'practitioner_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE practitioner_branches DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE practitioner_branches ADD CONSTRAINT fk_practitioner_branches_practitioners_same_org
        FOREIGN KEY (practitioner_id, organization_id)
        REFERENCES practitioners (id, organization_id) ON DELETE CASCADE;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'practitioner_branches'::regclass AND contype = 'f'
               AND confrelid = 'branches'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'practitioner_branches'::regclass AND attname = 'branch_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE practitioner_branches DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE practitioner_branches ADD CONSTRAINT fk_practitioner_branches_branches_same_org
        FOREIGN KEY (branch_id, organization_id)
        REFERENCES branches (id, organization_id) ON DELETE CASCADE;
    
COMMIT;

-- =========================================================================
--  catalog / 0004_seed_demo
-- =========================================================================

BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  scheduling / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model Schedule
--
CREATE TABLE "schedules" ("id" uuid NOT NULL PRIMARY KEY, "weekday" smallint NOT NULL CHECK ("weekday" >= 0), "start_time" time NOT NULL, "end_time" time NOT NULL, "slot_minutes" smallint NOT NULL CHECK ("slot_minutes" >= 0), "capacity" smallint NOT NULL CHECK ("capacity" >= 0), "valid_from" date NOT NULL, "valid_until" date NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "branch_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "practitioner_id" uuid NOT NULL, CONSTRAINT "uq_schedule_id_org" UNIQUE ("id", "organization_id"), CONSTRAINT "ck_schedule_time_order" CHECK ("end_time" > ("start_time")), CONSTRAINT "ck_schedule_weekday" CHECK (("weekday" >= 0 AND "weekday" <= 6)), CONSTRAINT "ck_schedule_slot_minutes" CHECK ("slot_minutes" > 0), CONSTRAINT "ck_schedule_capacity" CHECK ("capacity" >= 1));
--
-- Create model ScheduleBlock
--
CREATE TABLE "schedule_blocks" ("id" uuid NOT NULL PRIMARY KEY, "starts_at" timestamp with time zone NOT NULL, "ends_at" timestamp with time zone NOT NULL, "reason" varchar(12) NOT NULL, "note" varchar(200) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "branch_id" uuid NULL, "organization_id" uuid NOT NULL, "practitioner_id" uuid NULL, CONSTRAINT "uq_schedule_block_id_org" UNIQUE ("id", "organization_id"), CONSTRAINT "ck_schedule_block_time_order" CHECK ("ends_at" > ("starts_at")), CONSTRAINT "ck_schedule_block_reason" CHECK ("reason" IN ('vacation', 'holiday', 'leave', 'absence')));
ALTER TABLE "schedules" ADD CONSTRAINT "schedules_branch_id_daed9f34_fk_branches_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedules" ADD CONSTRAINT "schedules_organization_id_1129d432_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedules" ADD CONSTRAINT "schedules_practitioner_id_134e53e9_fk_practitioners_id" FOREIGN KEY ("practitioner_id") REFERENCES "practitioners" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "schedules_branch_id_daed9f34" ON "schedules" ("branch_id");
CREATE INDEX "schedules_organization_id_1129d432" ON "schedules" ("organization_id");
CREATE INDEX "schedules_practitioner_id_134e53e9" ON "schedules" ("practitioner_id");
ALTER TABLE "schedule_blocks" ADD CONSTRAINT "schedule_blocks_branch_id_e5bc9e27_fk_branches_id" FOREIGN KEY ("branch_id") REFERENCES "branches" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedule_blocks" ADD CONSTRAINT "schedule_blocks_organization_id_e1ce75a1_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedule_blocks" ADD CONSTRAINT "schedule_blocks_practitioner_id_e4be290b_fk_practitioners_id" FOREIGN KEY ("practitioner_id") REFERENCES "practitioners" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "schedule_blocks_branch_id_e5bc9e27" ON "schedule_blocks" ("branch_id");
CREATE INDEX "schedule_blocks_organization_id_e1ce75a1" ON "schedule_blocks" ("organization_id");
CREATE INDEX "schedule_blocks_practitioner_id_e4be290b" ON "schedule_blocks" ("practitioner_id");
COMMIT;

-- =========================================================================
--  scheduling / 0002_rls_policies
-- =========================================================================

BEGIN;
--
-- Raw SQL operation
--

            ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
            ALTER TABLE schedules FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON schedules
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE schedule_blocks ENABLE ROW LEVEL SECURITY;
            ALTER TABLE schedule_blocks FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON schedule_blocks
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'schedules'::regclass AND contype = 'f'
               AND confrelid = 'practitioners'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'schedules'::regclass AND attname = 'practitioner_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE schedules DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE schedules ADD CONSTRAINT fk_schedules_practitioners_same_org
        FOREIGN KEY (practitioner_id, organization_id)
        REFERENCES practitioners (id, organization_id) ON DELETE RESTRICT;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'schedules'::regclass AND contype = 'f'
               AND confrelid = 'branches'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'schedules'::regclass AND attname = 'branch_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE schedules DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE schedules ADD CONSTRAINT fk_schedules_branches_same_org
        FOREIGN KEY (branch_id, organization_id)
        REFERENCES branches (id, organization_id) ON DELETE RESTRICT;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'schedule_blocks'::regclass AND contype = 'f'
               AND confrelid = 'practitioners'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'schedule_blocks'::regclass AND attname = 'practitioner_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE schedule_blocks DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE schedule_blocks ADD CONSTRAINT fk_schedule_blocks_practitioners_same_org
        FOREIGN KEY (practitioner_id, organization_id)
        REFERENCES practitioners (id, organization_id) ON DELETE RESTRICT;
    

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'schedule_blocks'::regclass AND contype = 'f'
               AND confrelid = 'branches'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'schedule_blocks'::regclass AND attname = 'branch_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE schedule_blocks DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE schedule_blocks ADD CONSTRAINT fk_schedule_blocks_branches_same_org
        FOREIGN KEY (branch_id, organization_id)
        REFERENCES branches (id, organization_id) ON DELETE RESTRICT;
    
COMMIT;

-- =========================================================================
--  accounts / 0005_us06_audit
-- =========================================================================

BEGIN;
--
-- Add field user_agent to auditlog
--
ALTER TABLE "audit_log" ADD COLUMN "user_agent" varchar(300) DEFAULT '' NOT NULL;
ALTER TABLE "audit_log" ALTER COLUMN "user_agent" DROP DEFAULT;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  patients / 0002_us07_dependents
-- =========================================================================

BEGIN;
--
-- Add field relationship to patient
--
ALTER TABLE "patients" ADD COLUMN "relationship" varchar(20) DEFAULT '' NOT NULL;
ALTER TABLE "patients" ALTER COLUMN "relationship" DROP DEFAULT;
--
-- Create constraint ck_patient_relationship on model patient
--
ALTER TABLE "patients" ADD CONSTRAINT "ck_patient_relationship" CHECK ((("guardian_id" IS NULL AND "relationship" = '') OR ("guardian_id" IS NOT NULL AND NOT ("relationship" = ''))));
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  patients / 0003_us08_history
-- =========================================================================

BEGIN;
--
-- Create model PatientHistoryEntry
--
CREATE TABLE "patient_history_entries" ("id" uuid NOT NULL PRIMARY KEY, "kind" varchar(20) NOT NULL, "description" varchar(200) NOT NULL, "severity" varchar(20) NOT NULL, "source" varchar(20) NOT NULL, "recorded_at" date NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "declared_by_id" uuid NULL, "organization_id" uuid NOT NULL, "patient_id" uuid NOT NULL, CONSTRAINT "ck_history_severity" CHECK (("kind" = 'allergy' OR "severity" = '')));
ALTER TABLE "patient_history_entries" ADD CONSTRAINT "patient_history_entries_declared_by_id_dc8c9c7c_fk_users_id" FOREIGN KEY ("declared_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "patient_history_entries" ADD CONSTRAINT "patient_history_entr_organization_id_08c7573a_fk_organizat" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "patient_history_entries" ADD CONSTRAINT "patient_history_entries_patient_id_5d80aa15_fk_patients_id" FOREIGN KEY ("patient_id") REFERENCES "patients" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "patient_history_entries_declared_by_id_dc8c9c7c" ON "patient_history_entries" ("declared_by_id");
CREATE INDEX "patient_history_entries_organization_id_08c7573a" ON "patient_history_entries" ("organization_id");
CREATE INDEX "patient_history_entries_patient_id_5d80aa15" ON "patient_history_entries" ("patient_id");
CREATE INDEX "ix_history_patient" ON "patient_history_entries" ("patient_id", "is_active");
COMMIT;

-- =========================================================================
--  patients / 0004_us08_rls
-- =========================================================================

BEGIN;
--
-- Raw SQL operation
--

            ALTER TABLE patient_history_entries ENABLE ROW LEVEL SECURITY;
            ALTER TABLE patient_history_entries FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON patient_history_entries
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

    DO $do$
    DECLARE c text;
    BEGIN
        FOR c IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'patient_history_entries'::regclass AND contype = 'f'
               AND confrelid = 'patients'::regclass
               AND conkey = ARRAY[
                   (SELECT attnum FROM pg_attribute
                     WHERE attrelid = 'patient_history_entries'::regclass AND attname = 'patient_id')
               ]
        LOOP
            EXECUTE format('ALTER TABLE patient_history_entries DROP CONSTRAINT %I', c);
        END LOOP;
    END
    $do$;

    ALTER TABLE patient_history_entries ADD CONSTRAINT fk_patient_history_entries_patients_same_org
        FOREIGN KEY (patient_id, organization_id)
        REFERENCES patients (id, organization_id) ON DELETE CASCADE;
    
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  Como regenerar este archivo
--
--    backend/.venv/Scripts/python scripts/generar_esquema.py    (Windows)
--    backend/.venv/bin/python scripts/generar_esquema.py        (macOS/Linux)
--
--  Hay que regenerarlo cada vez que se agregue una migracion, para que la
--  documentacion no se separe de lo que realmente hay en la base.
-- =========================================================================
