-- =========================================================================
--  ESQUEMA REAL DEL SPRINT 0, GENERADO POR DJANGO
--
--  Este archivo NO se escribio a mano y NO se ejecuta. Es la salida de
--
--      python manage.py sqlmigrate <app> <migracion>
--
--  es decir, exactamente el SQL que Django envio a PostgreSQL al correr
--  "manage.py migrate". Sirve para dos cosas:
--
--    1. la documentacion del proyecto (el DDL real, no una aproximacion),
--    2. leer o revisar el modelo desde el SQL Editor de Supabase.
--
--  El esquema se aplica SIEMPRE con "manage.py migrate", nunca pegando
--  este archivo en una consola. Si se ejecutara, Django despues querria
--  crear tablas que ya existen.
--
--  Para regenerarlo, ver el pie del archivo.
-- =========================================================================


-- =========================================================================
--  accounts / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model User
--
CREATE TABLE "users" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "email" varchar(254) NOT NULL, "first_name" varchar(80) NOT NULL, "last_name" varchar(80) NOT NULL, "document_type" varchar(10) NOT NULL, "document_number" varchar(20) NOT NULL, "phone" varchar(30) NOT NULL, "birth_date" date NULL, "is_platform_admin" boolean NOT NULL, "is_active" boolean NOT NULL, "failed_login_attempts" smallint NOT NULL CHECK ("failed_login_attempts" >= 0), "locked_until" timestamp with time zone NULL, "last_login_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model AuditLog
--
CREATE TABLE "audit_log" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(60) NOT NULL, "entity" varchar(60) NOT NULL, "entity_id" varchar(64) NOT NULL, "detail" jsonb NOT NULL, "ip_address" inet NULL, "occurred_at" timestamp with time zone NOT NULL);
--
-- Create model LoginAttempt
--
CREATE TABLE "login_attempts" ("id" uuid NOT NULL PRIMARY KEY, "attempted_email" varchar(254) NOT NULL, "succeeded" boolean NOT NULL, "failure_reason" varchar(40) NOT NULL, "ip_address" inet NULL, "user_agent" varchar(300) NOT NULL, "occurred_at" timestamp with time zone NOT NULL);
--
-- Create model Permission
--
CREATE TABLE "permissions" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(80) NOT NULL UNIQUE, "module" varchar(40) NOT NULL, "description" varchar(200) NOT NULL);
--
-- Create model Role
--
CREATE TABLE "roles" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(40) NOT NULL, "name" varchar(80) NOT NULL, "description" varchar(200) NOT NULL, "is_system" boolean NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model RolePermission
--
CREATE TABLE "role_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "granted_at" timestamp with time zone NOT NULL);
--
-- Create model UserRole
--
CREATE TABLE "user_roles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "assigned_at" timestamp with time zone NOT NULL);
CREATE INDEX "permissions_code_c5331a5c_like" ON "permissions" ("code" varchar_pattern_ops);
COMMIT;

-- =========================================================================
--  tenancy / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model SubscriptionPlan
--
CREATE TABLE "subscription_plans" ("id" uuid NOT NULL PRIMARY KEY, "code" varchar(30) NOT NULL UNIQUE, "name" varchar(80) NOT NULL, "description" text NOT NULL, "monthly_price" numeric(10, 2) NOT NULL, "currency" varchar(3) NOT NULL, "max_branches" integer NULL CHECK ("max_branches" >= 0), "max_users" integer NULL CHECK ("max_users" >= 0), "max_practitioners" integer NULL CHECK ("max_practitioners" >= 0), "max_appointments_month" integer NULL CHECK ("max_appointments_month" >= 0), "max_ai_queries_month" integer NULL CHECK ("max_ai_queries_month" >= 0), "storage_mb" integer NULL CHECK ("storage_mb" >= 0), "features" jsonb NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model Organization
--
CREATE TABLE "organizations" ("id" uuid NOT NULL PRIMARY KEY, "slug" varchar(40) NOT NULL UNIQUE, "name" varchar(120) NOT NULL, "legal_name" varchar(160) NOT NULL, "tax_id" varchar(20) NOT NULL UNIQUE, "contact_email" varchar(254) NOT NULL, "contact_phone" varchar(30) NOT NULL, "address" varchar(200) NOT NULL, "city" varchar(80) NOT NULL, "country" varchar(2) NOT NULL, "logo_url" varchar(300) NOT NULL, "primary_color" varchar(7) NOT NULL, "secondary_color" varchar(7) NOT NULL, "timezone" varchar(40) NOT NULL, "status" varchar(12) NOT NULL, "onboarded_at" date NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, CONSTRAINT "ck_organization_status" CHECK ("status" IN ('active', 'suspended', 'inactive')));
--
-- Create model IsolationAlert
--
CREATE TABLE "isolation_alerts" ("id" uuid NOT NULL PRIMARY KEY, "alert_type" varchar(40) NOT NULL, "severity" varchar(10) NOT NULL, "description" varchar(300) NOT NULL, "endpoint" varchar(200) NOT NULL, "http_method" varchar(10) NOT NULL, "ip_address" inet NULL, "detail" jsonb NOT NULL, "status" varchar(12) NOT NULL, "occurred_at" timestamp with time zone NOT NULL, "resolved_at" timestamp with time zone NULL, "resolution_note" varchar(300) NOT NULL, "resolved_by_id" uuid NULL, "user_id" uuid NULL, "source_organization_id" uuid NULL, "target_organization_id" uuid NULL, CONSTRAINT "ck_alert_resolution" CHECK ((("resolved_at" IS NOT NULL AND "status" IN ('resolved', 'dismissed')) OR (NOT ("status" IN ('resolved', 'dismissed')) AND "resolved_at" IS NULL))));
--
-- Create model Subscription
--
CREATE TABLE "subscriptions" ("id" uuid NOT NULL PRIMARY KEY, "starts_at" date NOT NULL, "ends_at" date NULL, "status" varchar(12) NOT NULL, "change_reason" varchar(200) NOT NULL, "created_at" timestamp with time zone NOT NULL, "assigned_by_id" uuid NULL, "organization_id" uuid NOT NULL, "plan_id" uuid NOT NULL, CONSTRAINT "ck_subscription_period" CHECK (("ends_at" IS NULL OR "ends_at" >= ("starts_at"))));
--
-- Create model UsageMetric
--
CREATE TABLE "usage_metrics" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "metric_code" varchar(40) NOT NULL, "granularity" varchar(10) NOT NULL, "period_start" date NOT NULL, "value" numeric(14, 2) NOT NULL, "computed_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "uq_usage_metric" UNIQUE ("organization_id", "metric_code", "granularity", "period_start"));
CREATE INDEX "subscription_plans_code_28233073_like" ON "subscription_plans" ("code" varchar_pattern_ops);
CREATE INDEX "organizations_slug_aaafa6fa_like" ON "organizations" ("slug" varchar_pattern_ops);
CREATE INDEX "organizations_tax_id_8cb0fd40_like" ON "organizations" ("tax_id" varchar_pattern_ops);
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_resolved_by_id_6ae6191c_fk_users_id" FOREIGN KEY ("resolved_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_user_id_b9705ed8_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_source_organization__01300ea4_fk_organizat" FOREIGN KEY ("source_organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "isolation_alerts" ADD CONSTRAINT "isolation_alerts_target_organization__0accec3f_fk_organizat" FOREIGN KEY ("target_organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "isolation_alerts_resolved_by_id_6ae6191c" ON "isolation_alerts" ("resolved_by_id");
CREATE INDEX "isolation_alerts_user_id_b9705ed8" ON "isolation_alerts" ("user_id");
CREATE INDEX "isolation_alerts_source_organization_id_01300ea4" ON "isolation_alerts" ("source_organization_id");
CREATE INDEX "isolation_alerts_target_organization_id_0accec3f" ON "isolation_alerts" ("target_organization_id");
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_assigned_by_id_43e466d2_fk_users_id" FOREIGN KEY ("assigned_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_organization_id_b8dfd38b_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_plan_id_b857580e_fk_subscription_plans_id" FOREIGN KEY ("plan_id") REFERENCES "subscription_plans" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX "uq_subscription_active" ON "subscriptions" ("organization_id") WHERE "ends_at" IS NULL;
CREATE INDEX "subscriptions_assigned_by_id_43e466d2" ON "subscriptions" ("assigned_by_id");
CREATE INDEX "subscriptions_organization_id_b8dfd38b" ON "subscriptions" ("organization_id");
CREATE INDEX "subscriptions_plan_id_b857580e" ON "subscriptions" ("plan_id");
ALTER TABLE "usage_metrics" ADD CONSTRAINT "usage_metrics_organization_id_00852865_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "usage_metrics_organization_id_00852865" ON "usage_metrics" ("organization_id");
CREATE INDEX "ix_usage_metrics_period" ON "usage_metrics" ("period_start" DESC, "metric_code");
COMMIT;

-- =========================================================================
--  catalog / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model Branch
--
CREATE TABLE "branches" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(120) NOT NULL, "address" varchar(200) NOT NULL, "phone" varchar(30) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "uq_branch_name" UNIQUE ("organization_id", "name"), CONSTRAINT "uq_branch_id_org" UNIQUE ("id", "organization_id"));
ALTER TABLE "branches" ADD CONSTRAINT "branches_organization_id_49dd869c_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "branches_organization_id_49dd869c" ON "branches" ("organization_id");
COMMIT;

-- =========================================================================
--  accounts / 0002_initial
-- =========================================================================

BEGIN;
--
-- Add field branch to user
--
ALTER TABLE "users" ADD COLUMN "branch_id" uuid NULL CONSTRAINT "users_branch_id_d1b397ca_fk_branches_id" REFERENCES "branches"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_branch_id_d1b397ca_fk_branches_id" IMMEDIATE;
--
-- Add field organization to user
--
ALTER TABLE "users" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "users_organization_id_abe5d649_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "users_organization_id_abe5d649_fk_organizations_id" IMMEDIATE;
--
-- Add field organization to auditlog
--
ALTER TABLE "audit_log" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "audit_log_organization_id_385c33bb_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "audit_log_organization_id_385c33bb_fk_organizations_id" IMMEDIATE;
--
-- Add field user to auditlog
--
ALTER TABLE "audit_log" ADD COLUMN "user_id" uuid NULL CONSTRAINT "audit_log_user_id_a1b3392d_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "audit_log_user_id_a1b3392d_fk_users_id" IMMEDIATE;
--
-- Add field organization to loginattempt
--
ALTER TABLE "login_attempts" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "login_attempts_organization_id_43fcb601_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "login_attempts_organization_id_43fcb601_fk_organizations_id" IMMEDIATE;
--
-- Add field user to loginattempt
--
ALTER TABLE "login_attempts" ADD COLUMN "user_id" uuid NULL CONSTRAINT "login_attempts_user_id_8779072f_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "login_attempts_user_id_8779072f_fk_users_id" IMMEDIATE;
--
-- Add field organization to role
--
ALTER TABLE "roles" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "roles_organization_id_4b873032_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "roles_organization_id_4b873032_fk_organizations_id" IMMEDIATE;
--
-- Add field organization to rolepermission
--
ALTER TABLE "role_permissions" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "role_permissions_organization_id_bdb9f9aa_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "role_permissions_organization_id_bdb9f9aa_fk_organizations_id" IMMEDIATE;
--
-- Add field permission to rolepermission
--
ALTER TABLE "role_permissions" ADD COLUMN "permission_id" uuid NOT NULL CONSTRAINT "role_permissions_permission_id_ad343843_fk_permissions_id" REFERENCES "permissions"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "role_permissions_permission_id_ad343843_fk_permissions_id" IMMEDIATE;
--
-- Add field role to rolepermission
--
ALTER TABLE "role_permissions" ADD COLUMN "role_id" uuid NOT NULL CONSTRAINT "role_permissions_role_id_216516f2_fk_roles_id" REFERENCES "roles"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "role_permissions_role_id_216516f2_fk_roles_id" IMMEDIATE;
--
-- Add field assigned_by to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "assigned_by_id" uuid NULL CONSTRAINT "user_roles_assigned_by_id_a9db12d1_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_assigned_by_id_a9db12d1_fk_users_id" IMMEDIATE;
--
-- Add field organization to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "organization_id" uuid NULL CONSTRAINT "user_roles_organization_id_fe06d974_fk_organizations_id" REFERENCES "organizations"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_organization_id_fe06d974_fk_organizations_id" IMMEDIATE;
--
-- Add field role to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "role_id" uuid NOT NULL CONSTRAINT "user_roles_role_id_816a4486_fk_roles_id" REFERENCES "roles"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_role_id_816a4486_fk_roles_id" IMMEDIATE;
--
-- Add field user to userrole
--
ALTER TABLE "user_roles" ADD COLUMN "user_id" uuid NOT NULL CONSTRAINT "user_roles_user_id_9d9f8dbb_fk_users_id" REFERENCES "users"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "user_roles_user_id_9d9f8dbb_fk_users_id" IMMEDIATE;
--
-- Create constraint uq_user_email on model user
--
ALTER TABLE "users" ADD CONSTRAINT "uq_user_email" UNIQUE ("organization_id", "email");
--
-- Create constraint uq_user_document on model user
--
ALTER TABLE "users" ADD CONSTRAINT "uq_user_document" UNIQUE ("organization_id", "document_number");
--
-- Create constraint uq_user_email_platform on model user
--
CREATE UNIQUE INDEX "uq_user_email_platform" ON "users" ("email") WHERE "organization_id" IS NULL;
--
-- Create constraint uq_user_id_org on model user
--
ALTER TABLE "users" ADD CONSTRAINT "uq_user_id_org" UNIQUE ("id", "organization_id");
--
-- Create constraint ck_user_scope on model user
--
ALTER TABLE "users" ADD CONSTRAINT "ck_user_scope" CHECK ((("is_platform_admin" AND "organization_id" IS NULL) OR (NOT "is_platform_admin" AND "organization_id" IS NOT NULL)));
--
-- Create index ix_audit_log_org on field(s) organization, -occurred_at of model auditlog
--
CREATE INDEX "ix_audit_log_org" ON "audit_log" ("organization_id", "occurred_at" DESC);
--
-- Create index ix_login_attempts_email on field(s) attempted_email, -occurred_at of model loginattempt
--
CREATE INDEX "ix_login_attempts_email" ON "login_attempts" ("attempted_email", "occurred_at" DESC);
--
-- Create constraint uq_role_code_org on model role
--
CREATE UNIQUE INDEX "uq_role_code_org" ON "roles" ("organization_id", "code") WHERE "organization_id" IS NOT NULL;
--
-- Create constraint uq_role_code_system on model role
--
CREATE UNIQUE INDEX "uq_role_code_system" ON "roles" ("code") WHERE "organization_id" IS NULL;
--
-- Create constraint ck_role_system on model role
--
ALTER TABLE "roles" ADD CONSTRAINT "ck_role_system" CHECK ((NOT "is_system" OR "organization_id" IS NULL));
--
-- Create constraint uq_role_id_org on model role
--
ALTER TABLE "roles" ADD CONSTRAINT "uq_role_id_org" UNIQUE ("id", "organization_id");
--
-- Create constraint uq_role_permission on model rolepermission
--
ALTER TABLE "role_permissions" ADD CONSTRAINT "uq_role_permission" UNIQUE ("role_id", "permission_id");
--
-- Create constraint uq_user_role on model userrole
--
ALTER TABLE "user_roles" ADD CONSTRAINT "uq_user_role" UNIQUE ("user_id", "role_id");
CREATE INDEX "users_branch_id_d1b397ca" ON "users" ("branch_id");
CREATE INDEX "users_organization_id_abe5d649" ON "users" ("organization_id");
CREATE INDEX "audit_log_organization_id_385c33bb" ON "audit_log" ("organization_id");
CREATE INDEX "audit_log_user_id_a1b3392d" ON "audit_log" ("user_id");
CREATE INDEX "login_attempts_organization_id_43fcb601" ON "login_attempts" ("organization_id");
CREATE INDEX "login_attempts_user_id_8779072f" ON "login_attempts" ("user_id");
CREATE INDEX "roles_organization_id_4b873032" ON "roles" ("organization_id");
CREATE INDEX "role_permissions_organization_id_bdb9f9aa" ON "role_permissions" ("organization_id");
CREATE INDEX "role_permissions_permission_id_ad343843" ON "role_permissions" ("permission_id");
CREATE INDEX "role_permissions_role_id_216516f2" ON "role_permissions" ("role_id");
CREATE INDEX "user_roles_assigned_by_id_a9db12d1" ON "user_roles" ("assigned_by_id");
CREATE INDEX "user_roles_organization_id_fe06d974" ON "user_roles" ("organization_id");
CREATE INDEX "user_roles_role_id_816a4486" ON "user_roles" ("role_id");
CREATE INDEX "user_roles_user_id_9d9f8dbb" ON "user_roles" ("user_id");
COMMIT;

-- =========================================================================
--  patients / 0001_initial
-- =========================================================================

BEGIN;
--
-- Create model Patient
--
CREATE TABLE "patients" ("id" uuid NOT NULL PRIMARY KEY, "document_type" varchar(10) NOT NULL, "document_number" varchar(20) NULL, "first_name" varchar(80) NOT NULL, "last_name" varchar(80) NOT NULL, "birth_date" date NULL, "sex" varchar(1) NULL, "phone" varchar(30) NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "guardian_id" uuid NULL, "organization_id" uuid NOT NULL, "user_id" uuid NULL UNIQUE, CONSTRAINT "ck_patient_guardian" CHECK (NOT ("guardian_id" = ("id") AND "guardian_id" IS NOT NULL)), CONSTRAINT "uq_patient_id_org" UNIQUE ("id", "organization_id"), CONSTRAINT "ck_patient_doc_or_guardian" CHECK (("document_number" IS NOT NULL OR "guardian_id" IS NOT NULL)));
ALTER TABLE "patients" ADD CONSTRAINT "patients_guardian_id_0190b7d7_fk_patients_id" FOREIGN KEY ("guardian_id") REFERENCES "patients" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "patients" ADD CONSTRAINT "patients_organization_id_a6f5b5b9_fk_organizations_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "patients" ADD CONSTRAINT "patients_user_id_11c42fa7_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX "uq_patient_document" ON "patients" ("organization_id", "document_type", "document_number") WHERE "document_number" IS NOT NULL;
CREATE INDEX "patients_guardian_id_0190b7d7" ON "patients" ("guardian_id");
CREATE INDEX "patients_organization_id_a6f5b5b9" ON "patients" ("organization_id");
COMMIT;

-- =========================================================================
--  tenancy / 0002_rls_policies
-- =========================================================================

BEGIN;
--
-- Raw SQL operation
--

CREATE OR REPLACE FUNCTION app_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE
    AS $fn$ SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid $fn$;

CREATE OR REPLACE FUNCTION app_is_platform_admin() RETURNS boolean
    LANGUAGE sql STABLE
    AS $fn$ SELECT coalesce(current_setting('app.is_platform_admin', true) = 'on', false) $fn$;

-- Resuelve el inquilino a partir de su slug, para el formulario de login.
--
-- Existe por un problema del huevo y la gallina: antes de autenticar no hay
-- contexto, así que un SELECT sobre organizations devolvería cero filas por
-- la propia política, y el login nunca podría empezar.
--
-- Devuelve UNA columna —el uuid— y sólo de organizaciones activas. No permite
-- enumerar: hay que conocer el slug exacto de antemano. El permiso de
-- plataforma se activa y se restaura dentro de la misma llamada, de modo que
-- no sobrevive al retorno de la función.
CREATE OR REPLACE FUNCTION app_resolve_tenant(p_slug text) RETURNS uuid
    LANGUAGE plpgsql VOLATILE
    AS $fn$
DECLARE
    v_id   uuid;
    v_prev text;
BEGIN
    v_prev := coalesce(current_setting('app.is_platform_admin', true), '');
    PERFORM set_config('app.is_platform_admin', 'on', true);
    SELECT id INTO v_id FROM organizations
     WHERE slug = p_slug AND status = 'active';
    PERFORM set_config('app.is_platform_admin', v_prev, true);
    RETURN v_id;
END
$fn$;

--
-- Raw SQL operation
--

-- users.branch debe pertenecer a la misma organización que el usuario.
DO $do$
DECLARE c text;
BEGIN
    SELECT conname INTO c FROM pg_constraint
     WHERE conrelid = 'users'::regclass AND contype = 'f'
       AND confrelid = 'branches'::regclass;
    IF c IS NOT NULL THEN
        EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', c);
    END IF;
END
$do$;

ALTER TABLE users ADD CONSTRAINT fk_user_branch_same_org
    FOREIGN KEY (branch_id, organization_id)
    REFERENCES branches (id, organization_id) ON DELETE SET NULL (branch_id);

-- patients.user debe pertenecer a la misma organización que el paciente.
DO $do$
DECLARE c text;
BEGIN
    SELECT conname INTO c FROM pg_constraint
     WHERE conrelid = 'patients'::regclass AND contype = 'f'
       AND confrelid = 'users'::regclass;
    IF c IS NOT NULL THEN
        EXECUTE format('ALTER TABLE patients DROP CONSTRAINT %I', c);
    END IF;
END
$do$;

ALTER TABLE patients ADD CONSTRAINT fk_patient_user_same_org
    FOREIGN KEY (user_id, organization_id)
    REFERENCES users (id, organization_id) ON DELETE SET NULL (user_id);

-- El titular de un paciente debe ser de la misma organización.
DO $do$
DECLARE c text;
BEGIN
    SELECT conname INTO c FROM pg_constraint
     WHERE conrelid = 'patients'::regclass AND contype = 'f'
       AND confrelid = 'patients'::regclass;
    IF c IS NOT NULL THEN
        EXECUTE format('ALTER TABLE patients DROP CONSTRAINT %I', c);
    END IF;
END
$do$;

ALTER TABLE patients ADD CONSTRAINT fk_patient_guardian_same_org
    FOREIGN KEY (guardian_id, organization_id)
    REFERENCES patients (id, organization_id) ON DELETE SET NULL (guardian_id);

-- Un inquilino no puede asignarse un rol de otro.
DO $do$
DECLARE c text;
BEGIN
    FOR c IN
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'role_permissions'::regclass AND contype = 'f'
           AND confrelid = 'roles'::regclass
    LOOP
        EXECUTE format('ALTER TABLE role_permissions DROP CONSTRAINT %I', c);
    END LOOP;
    FOR c IN
        SELECT conname FROM pg_constraint
         WHERE conrelid = 'user_roles'::regclass AND contype = 'f'
           AND confrelid = 'roles'::regclass
    LOOP
        EXECUTE format('ALTER TABLE user_roles DROP CONSTRAINT %I', c);
    END LOOP;
END
$do$;

ALTER TABLE role_permissions ADD CONSTRAINT fk_role_permission_role_same_org
    FOREIGN KEY (role_id, organization_id)
    REFERENCES roles (id, organization_id) ON DELETE CASCADE;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_role_role_same_org
    FOREIGN KEY (role_id, organization_id)
    REFERENCES roles (id, organization_id) ON DELETE RESTRICT;

--
-- Raw SQL operation
--

CREATE OR REPLACE VIEW v_organization_current_plan AS
SELECT o.id        AS organization_id,
       o.name      AS organization_name,
       o.status    AS organization_status,
       o.onboarded_at,
       s.id        AS subscription_id,
       s.starts_at AS subscription_starts_at,
       p.id        AS plan_id,
       p.code      AS plan_code,
       p.name      AS plan_name,
       p.max_users,
       p.max_branches,
       p.max_appointments_month,
       p.max_ai_queries_month,
       p.storage_mb
FROM organizations o
LEFT JOIN subscriptions s
       ON s.organization_id = o.id AND s.ends_at IS NULL
LEFT JOIN subscription_plans p
       ON p.id = s.plan_id;

--
-- Raw SQL operation
--

            ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
            ALTER TABLE branches FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON branches
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
            ALTER TABLE roles FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON roles
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
            ALTER TABLE role_permissions FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON role_permissions
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
            ALTER TABLE user_roles FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON user_roles
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        

            ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
            ALTER TABLE patients FORCE  ROW LEVEL SECURITY;
            CREATE POLICY tenant_isolation ON patients
                USING (organization_id = app_current_tenant())
                WITH CHECK (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

-- roles y role_permissions: las plantillas del sistema (organization_id NULL)
-- las LEE cualquier inquilino, para poder clonarlas al dar de alta una
-- organización; sólo el superadministrador las ESCRIBE.
--
-- Sin la política de escritura, la migración semilla falla: Django corre las
-- migraciones como app_user, sujeto a RLS.
CREATE POLICY system_templates_read ON roles
    FOR SELECT USING (organization_id IS NULL);
CREATE POLICY system_templates_write ON roles
    USING (organization_id IS NULL AND app_is_platform_admin())
    WITH CHECK (organization_id IS NULL AND app_is_platform_admin());

CREATE POLICY system_templates_read ON role_permissions
    FOR SELECT USING (organization_id IS NULL);
CREATE POLICY system_templates_write ON role_permissions
    USING (organization_id IS NULL AND app_is_platform_admin())
    WITH CHECK (organization_id IS NULL AND app_is_platform_admin());

-- users: el superadministrador debe poder verse a sí mismo para iniciar
-- sesión, pero no a los usuarios de ninguna organización.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON users
    USING (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    )
    WITH CHECK (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    );

-- audit_log: mismo patrón que users. El superadministrador audita sus propias
-- acciones (alta de organización, asignación de plan) con organization_id
-- NULL, y no ve la bitácora de ningún inquilino.
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON audit_log
    USING (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    )
    WITH CHECK (
        organization_id = app_current_tenant()
        OR (app_is_platform_admin() AND organization_id IS NULL)
    );

-- organizations: el superadmin las administra todas; cada inquilino sólo lee
-- su propia ficha, que necesita para el logo y los colores.
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations FORCE  ROW LEVEL SECURITY;
CREATE POLICY platform_admin_all ON organizations
    USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
CREATE POLICY tenant_reads_itself ON organizations
    FOR SELECT USING (id = app_current_tenant());

-- subscription_plans: catálogo legible por todos, escribible sólo por el
-- superadministrador.
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans FORCE  ROW LEVEL SECURITY;
CREATE POLICY plans_readable ON subscription_plans FOR SELECT USING (true);
CREATE POLICY plans_writable ON subscription_plans
    USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());

--
-- Raw SQL operation
--

            ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
            ALTER TABLE subscriptions FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_all ON subscriptions
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY tenant_reads_itself ON subscriptions
                FOR SELECT USING (organization_id = app_current_tenant());
        

            ALTER TABLE usage_metrics ENABLE ROW LEVEL SECURITY;
            ALTER TABLE usage_metrics FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_all ON usage_metrics
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY tenant_reads_itself ON usage_metrics
                FOR SELECT USING (organization_id = app_current_tenant());
        
--
-- Raw SQL operation
--

            ALTER TABLE isolation_alerts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE isolation_alerts FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_manages ON isolation_alerts
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY anyone_reports ON isolation_alerts
                FOR INSERT WITH CHECK (true);
        

            ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
            ALTER TABLE login_attempts FORCE  ROW LEVEL SECURITY;
            CREATE POLICY platform_admin_manages ON login_attempts
                USING (app_is_platform_admin()) WITH CHECK (app_is_platform_admin());
            CREATE POLICY anyone_reports ON login_attempts
                FOR INSERT WITH CHECK (true);
        
--
-- Raw SQL operation
--

REVOKE UPDATE, DELETE ON audit_log      FROM CURRENT_USER;
REVOKE UPDATE, DELETE ON login_attempts FROM CURRENT_USER;

COMMIT;

-- =========================================================================
--  tenancy / 0003_seed_catalog
-- =========================================================================

BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- =========================================================================
--  Como regenerar este archivo
--
--    backend/.venv/Scripts/python scripts/generar_esquema.py    (Windows)
--    backend/.venv/bin/python scripts/generar_esquema.py        (macOS/Linux)
--
--  Hay que regenerarlo cada vez que se agregue una migracion, para que la
--  documentacion no se separe de lo que realmente hay en la base.
-- =========================================================================
