# Generated by Django 5.2.17 on 2026-09-05 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0003_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='America/La_Paz', max_length=40),
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('license_number', models.CharField(blank=True, default='', max_length=40, verbose_name='matrícula')),
                ('search_name', models.CharField(default='', editable=False, max_length=170)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioners', to='tenancy.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'db_table': 'practitioners',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerBranch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_links', to='catalog.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_branches', to='tenancy.organization')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='catalog.practitioner')),
            ],
            options={
                'verbose_name': 'sucursal de profesional',
                'verbose_name_plural': 'sucursales de profesional',
                'db_table': 'practitioner_branches',
                'ordering': ['practitioner_id', 'branch_id'],
            },
        ),
        migrations.AddField(
            model_name='practitioner',
            name='branches',
            field=models.ManyToManyField(related_name='practitioners', through='catalog.PractitionerBranch', to='catalog.branch'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialties', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
                'db_table': 'specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerSpecialty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_specialties', to='tenancy.organization')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_links', to='catalog.practitioner')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_links', to='catalog.specialty')),
            ],
            options={
                'verbose_name': 'especialidad de profesional',
                'verbose_name_plural': 'especialidades de profesional',
                'db_table': 'practitioner_specialties',
                'ordering': ['practitioner_id', 'specialty_id'],
            },
        ),
        migrations.AddField(
            model_name='practitioner',
            name='specialties',
            field=models.ManyToManyField(related_name='practitioners', through='catalog.PractitionerSpecialty', to='catalog.specialty'),
        ),
        migrations.CreateModel(
            name='BranchHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='catalog.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_hours', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'horario de sucursal',
                'verbose_name_plural': 'horarios de sucursal',
                'db_table': 'branch_hours',
                'ordering': ['branch_id', 'weekday', 'opens_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='ck_branch_hours_weekday'), models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='ck_branch_hours_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='practitionerbranch',
            constraint=models.UniqueConstraint(fields=('practitioner', 'branch'), name='uq_practitioner_branch'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_specialty_name'),
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='uq_specialty_id_org'),
        ),
        migrations.AddConstraint(
            model_name='practitionerspecialty',
            constraint=models.UniqueConstraint(fields=('practitioner', 'specialty'), name='uq_practitioner_specialty'),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='uq_practitioner_id_org'),
        ),
        migrations.AddConstraint(
            model_name='practitioner',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number', ''), _negated=True), fields=('organization', 'license_number'), name='uq_practitioner_license'),
        ),
    ]
