# Generated by Django 5.2.17 on 2026-10-02 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_demo'),
        ('tenancy', '0004_organization_cancellation_notice_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('consultation', 'Consulta'), ('study', 'Estudio'), ('procedure', 'Procedimiento')], default='study', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('preparation', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='tenancy.organization')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.specialty')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'services',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='uq_service_name'), models.UniqueConstraint(fields=('id', 'organization'), name='uq_service_id_org'), models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='ck_service_price')],
            },
        ),
    ]
