# Generated by Django 5.2.17 on 2026-09-16 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_seed_demo"),
        ("patients", "0004_us08_rls"),
        ("scheduling", "0002_rls_policies"),
        ("tenancy", "0003_seed_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pendiente de pago"),
                            ("confirmed", "Confirmada"),
                            ("attended", "Atendida"),
                            ("cancelled", "Cancelada"),
                            ("rescheduled", "Reprogramada"),
                            ("expired", "Vencida"),
                            ("no_show", "Ausente"),
                        ],
                        default="pending_payment",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("patient", "El paciente canceló"),
                            ("no_show_policy", "Vencida por falta de pago"),
                            ("organization", "La organización canceló"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("refund_eligible", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="catalog.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="catalog.practitioner",
                    ),
                ),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reschedules_to",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="scheduling.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "ficha",
                "verbose_name_plural": "fichas",
                "db_table": "appointments",
                "ordering": ["-starts_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "organization"), name="uq_appointment_id_org"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["pending_payment", "confirmed"])
                        ),
                        fields=("schedule", "starts_at"),
                        name="uq_appointment_active_slot",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="ck_appointment_time_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "pending_payment",
                                    "confirmed",
                                    "attended",
                                    "cancelled",
                                    "rescheduled",
                                    "expired",
                                    "no_show",
                                ],
                            )
                        ),
                        name="ck_appointment_status",
                    ),
                ],
            },
        ),
    ]
