# Generated by Django 5.2.17 on 2026-10-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendance_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
