# Generated by Django 5.2.17 on 2026-09-06 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_rls_policies'),
        ('tenancy', '0003_seed_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='catalog.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='tenancy.organization')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='catalog.practitioner')),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
                'db_table': 'schedules',
                'ordering': ['practitioner_id', 'weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('id', 'organization'), name='uq_schedule_id_org'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='ck_schedule_time_order'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='ck_schedule_weekday'), models.CheckConstraint(condition=models.Q(('slot_minutes__gt', 0)), name='ck_schedule_slot_minutes'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='ck_schedule_capacity')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacaciones'), ('holiday', 'Feriado'), ('leave', 'Licencia'), ('absence', 'Ausencia imprevista')], max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_blocks', to='catalog.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_blocks', to='tenancy.organization')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_blocks', to='catalog.practitioner')),
            ],
            options={
                'verbose_name': 'bloqueo de agenda',
                'verbose_name_plural': 'bloqueos de agenda',
                'db_table': 'schedule_blocks',
                'ordering': ['-starts_at'],
                'constraints': [models.UniqueConstraint(fields=('id', 'organization'), name='uq_schedule_block_id_org'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_schedule_block_time_order'), models.CheckConstraint(condition=models.Q(('reason__in', ['vacation', 'holiday', 'leave', 'absence'])), name='ck_schedule_block_reason')],
            },
        ),
    ]
