# Generated by Django 5.2.17 on 2026-10-04 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_attendance_confirmed_at'),
        ('tenancy', '0005_backup_por_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('simulated', 'Simulado')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Pagado'), ('failed', 'Fallido'), ('expired', 'Vencido'), ('refunded', 'Devuelto')], default='pending', max_length=12)),
                ('provider_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('checkout_url', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='appointments.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('id', 'organization'), name='uq_payment_id_org'), models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('appointment',), name='uq_payment_one_success'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount')],
            },
        ),
    ]
