# Generated by Django 5.2.17 on 2026-10-03 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_rls_policies'),
        ('catalog', '0007_us32_permisos_servicios'),
        ('patients', '0004_us08_rls'),
        ('tenancy', '0004_organization_cancellation_notice_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmado')], default='draft', max_length=10)),
                ('reason', models.TextField(blank=True, default='', verbose_name='motivo de consulta')),
                ('evolution', models.TextField(blank=True, default='', verbose_name='evolución')),
                ('diagnosis', models.TextField(blank=True, default='', verbose_name='diagnóstico')),
                ('indications', models.TextField(blank=True, default='', verbose_name='indicaciones')),
                ('treatment', models.TextField(blank=True, default='', verbose_name='tratamiento')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='encounter', to='appointments.appointment')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='catalog.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='tenancy.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='catalog.practitioner')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'encuentro clínico',
                'verbose_name_plural': 'encuentros clínicos',
                'db_table': 'encounters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncounterAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('reason', 'Motivo de consulta'), ('evolution', 'Evolución'), ('diagnosis', 'Diagnóstico'), ('indications', 'Indicaciones'), ('treatment', 'Tratamiento')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_amendments', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='encounters.encounter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_amendments', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'enmienda',
                'verbose_name_plural': 'enmiendas',
                'db_table': 'encounter_amendments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', '-created_at'], name='ix_encounter_patient'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='uq_encounter_id_org'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'signed'])), name='ck_encounter_status'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('signed_at__isnull', True), ('signed_by__isnull', True), ('status', 'draft')), models.Q(('signed_at__isnull', False), ('signed_by__isnull', False), ('status', 'signed')), _connector='OR'), name='ck_encounter_signature'),
        ),
    ]
