# Generated by Django 5.2.17 on 2026-10-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_seed_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogfragment',
            name='source_type',
            field=models.CharField(choices=[('specialty', 'Especialidad'), ('branch', 'Sucursal'), ('service', 'Servicio o estudio'), ('policy', 'Política de la organización')], max_length=20),
        ),
    ]
