# Generated by Django 5.2.17 on 2026-08-23 20:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('max_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('max_practitioners', models.PositiveIntegerField(blank=True, null=True)),
                ('max_appointments_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ai_queries_month', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan de suscripción',
                'verbose_name_plural': 'planes de suscripción',
                'db_table': 'subscription_plans',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([a-z0-9-]{1,38}[a-z0-9])$', 'Sólo minúsculas, números y guiones; entre 3 y 40 caracteres.')])),
                ('name', models.CharField(max_length=120)),
                ('legal_name', models.CharField(max_length=160)),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(default='BO', max_length=2)),
                ('logo_url', models.URLField(blank=True, default='', max_length=300)),
                ('primary_color', models.CharField(default='#0F766E', max_length=7)),
                ('secondary_color', models.CharField(default='#134E4A', max_length=7)),
                ('timezone', models.CharField(default='America/La_Paz', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('inactive', 'Inactiva')], default='active', max_length=12)),
                ('onboarded_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'db_table': 'organizations',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'inactive'])), name='ck_organization_status')],
            },
        ),
        migrations.CreateModel(
            name='IsolationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('cross_tenant_access', 'Acceso cruzado entre inquilinos'), ('missing_tenant_context', 'Petición sin contexto de inquilino'), ('jwt_tenant_mismatch', 'El token no coincide con el inquilino'), ('rls_denied', 'Rechazado por Row Level Security'), ('plan_limit_exceeded', 'Límite del plan superado')], max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('endpoint', models.CharField(blank=True, default='', max_length=200)),
                ('http_method', models.CharField(blank=True, default='', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='pending', max_length=12)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=300)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_isolation_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_alerts', to=settings.AUTH_USER_MODEL)),
                ('source_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_alerts_raised', to='tenancy.organization')),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_alerts_targeted', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'alerta de aislamiento',
                'verbose_name_plural': 'alertas de aislamiento',
                'db_table': 'isolation_alerts',
                'ordering': ['-occurred_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status__in', ['resolved', 'dismissed'])), models.Q(models.Q(('status__in', ['resolved', 'dismissed']), _negated=True), ('resolved_at__isnull', True)), _connector='OR'), name='ck_alert_resolution')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Vencida')], default='active', max_length=12)),
                ('change_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.subscriptionplan')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'db_table': 'subscriptions',
                'ordering': ['-starts_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ends_at__isnull', True)), fields=('organization',), name='uq_subscription_active'), models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='ck_subscription_period')],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{2,39}$')])),
                ('granularity', models.CharField(choices=[('day', 'Diaria'), ('month', 'Mensual')], default='day', max_length=10)),
                ('period_start', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'métrica de uso',
                'verbose_name_plural': 'métricas de uso',
                'db_table': 'usage_metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['-period_start', 'metric_code'], name='ix_usage_metrics_period')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'metric_code', 'granularity', 'period_start'), name='uq_usage_metric')],
            },
        ),
    ]
