# Generated by Django 5.2.17 on 2026-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_seed_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="cancellation_notice_hours",
            field=models.PositiveIntegerField(default=24),
        ),
    ]
